import React, { useState } from 'react';
import { Alert, Text, View } from 'react-native';
import { Screen, Title, Body, Surface, Button, Field, Divider, Chip } from '../components/ui';
import { useCart } from '../context/CartContext';
import { useTheme } from '../context/ThemeContext';
export default function CartScreen({ navigation }) {
 const {state,dispatch}=useCart();const {colors}=useTheme();const [promo,setPromo]=useState('');const [orderType,setOrderType]=useState('Takeaway');const [table,setTable]=useState('');const [pickup,setPickup]=useState('ASAP');
 const total=state.items.reduce((s,x)=>s+x.quantity,0);
 const goSummary=()=>{if(!total)return;const info=orderType==='Dine-in'?`Table ${table||'T3'}`:`Pickup ${pickup||'in 25 minutes'}`;navigation.getParent()?.navigate('OrderSummary',{orderType,tableOrTime:info});};
 return <Screen scroll><Title>Your cart</Title><Body style={{ marginTop:5 }}>{total} item{total===1?'':'s'} · {state.items.length} dish{state.items.length===1?'':'es'}</Body>
 {state.items.length===0?<Surface style={{ marginTop:18,alignItems:'center',gap:9 }}><Text style={{ fontSize:38 }}>🛍</Text><Title size={19}>Your cart is waiting</Title><Body style={{ textAlign:'center' }}>Add something delicious from today’s menu.</Body><Button title="Browse menu" onPress={()=>navigation.getParent()?.navigate('Tabs',{screen:'Menu'})} style={{ marginTop:4 }}/></Surface>:<>
 {state.items.map((item)=><Surface key={item.id} style={{ marginTop:12 }}><View style={{ flexDirection:'row',justifyContent:'space-between',gap:12 }}><View style={{ flex:1 }}><Text style={{ color:colors.text,fontWeight:'800',fontSize:16 }}>{item.name}</Text><Body>Rs {item.price} each</Body></View><Text style={{ color:colors.primary,fontWeight:'900' }}>Rs {item.price*item.quantity}</Text></View><View style={{ flexDirection:'row',alignItems:'center',gap:10,marginTop:14 }}><Button title="−" secondary onPress={()=>dispatch({type:'DECREMENT',id:item.id})} style={{ minHeight:36,minWidth:40,paddingHorizontal:8 }}/><Text style={{ color:colors.text,fontWeight:'900' }}>{item.quantity}</Text><Button title="+" secondary onPress={()=>dispatch({type:'INCREMENT',id:item.id})} style={{ minHeight:36,minWidth:40,paddingHorizontal:8 }}/><Button title="Remove" secondary onPress={()=>dispatch({type:'REMOVE_ITEM',id:item.id})} style={{ marginLeft:'auto',minHeight:36 }}/></View><Field label="Special instructions" value={item.note} onChangeText={(note)=>dispatch({type:'UPDATE_NOTE',id:item.id,note})} placeholder="e.g. no onions" style={{ minHeight:40 }}/></Surface>)}
 <Surface style={{ marginTop:14 }}><Title size={17}>Promo code</Title><View style={{ flexDirection:'row',alignItems:'flex-start',gap:8,marginTop:10 }}><View style={{ flex:1 }}><Field label="" value={promo} onChangeText={setPromo} placeholder="WELCOME10" error={state.promoError}/></View><Button title="Apply" onPress={()=>dispatch({type:'APPLY_PROMO',code:promo})}/></View>{state.promoCode?<View style={{ flexDirection:'row',justifyContent:'space-between' }}><Body>{state.promoCode} · {state.discountPercent}% off</Body><Text onPress={()=>dispatch({type:'REMOVE_PROMO'})} style={{ color:colors.primary,fontWeight:'800' }}>Remove</Text></View>:null}</Surface>
 <Surface style={{ marginTop:14 }}><Title size={17}>How would you like it?</Title><View style={{ flexDirection:'row',gap:8,marginTop:12 }}><Chip label="Takeaway" selected={orderType==='Takeaway'} onPress={()=>setOrderType('Takeaway')}/><Chip label="Dine-in" selected={orderType==='Dine-in'} onPress={()=>setOrderType('Dine-in')}/></View>{orderType==='Dine-in'?<Field label="Table number" value={table} onChangeText={setTable} placeholder="T3"/>:<Field label="Pickup time" value={pickup} onChangeText={setPickup} placeholder="ASAP or 19:30"/>}</Surface>
 <Button title="Review order" onPress={goSummary} style={{ marginTop:16 }}/><Text onPress={()=>Alert.alert('Frontend demo','This prototype uses local mock data; no real payment is collected.')} style={{ color:colors.muted,textAlign:'center',marginTop:12,fontSize:12 }}>No payment is taken in this demo.</Text></>}</Screen>;
}
