import React, { useState } from 'react';
import { Alert, Text, View } from 'react-native';
import { Screen, Title, Body, Surface, Button, Chip, Field } from '../components/ui';
import { useOrders } from '../context/OrdersContext';
import { useReservation } from '../hooks/useReservation';
import { useMenu } from '../context/MenuContext';
import { useTheme } from '../context/ThemeContext';
export default function ManagerDashboardScreen() {
 const [tab,setTab]=useState('Orders');const [name,setName]=useState('');const [price,setPrice]=useState('');const [category,setCategory]=useState('Mains');const {orders,dispatch}=useOrders();const r=useReservation();const {items,updateItem,addItem}=useMenu();const {colors}=useTheme();
 const changeStatus=(order,status)=>dispatch({type:'STATUS',id:order.id,status});
 return <Screen scroll><Text style={{ color:colors.primary,fontWeight:'900',letterSpacing:1.2,fontSize:11 }}>RESTAURANT OPERATIONS</Text><Title style={{ marginTop:5 }}>Manager dashboard</Title><Body style={{ marginTop:5 }}>Changes are shared with the customer screens.</Body><View style={{ flexDirection:'row',gap:7,marginTop:16,marginBottom:13 }}>{['Orders','Reservations','Menu'].map((x)=><Chip key={x} label={x} selected={tab===x} onPress={()=>setTab(x)}/>)}</View>
 {tab==='Orders'?orders.length?orders.map((order)=><Surface key={order.id} style={{ marginBottom:10 }}><View style={{ flexDirection:'row',justifyContent:'space-between' }}><Text style={{ color:colors.text,fontWeight:'900' }}>#{order.id.slice(-6).toUpperCase()}</Text><Text style={{ color:colors.primary,fontWeight:'800' }}>{order.status}</Text></View><Body style={{ marginTop:6 }}>{order.items.map((x)=>`${x.quantity}× ${x.name}`).join(', ')}</Body><Body>Rs {order.total} · {order.type} · {order.tableOrTime||''}</Body><View style={{ flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:12 }}>{['Preparing','Ready','Served','Cancelled'].map((s)=><Button key={s} title={s} secondary onPress={()=>changeStatus(order,s)} style={{ minHeight:36,paddingHorizontal:10 }}/>)}</View></Surface>):<Surface><Body>No incoming orders yet. Customer orders will appear here.</Body></Surface>:null}
 {tab==='Reservations'?r.reservations.filter((x)=>x.status!=='cancelled').map((item)=><Surface key={item.id} style={{ marginBottom:10 }}><Text style={{ color:colors.text,fontWeight:'800' }}>{item.date} · {item.time} · {item.partySize} guests</Text><Body>{item.contactName||item.name||'Guest'} · {item.phone} · {item.tableId} · {item.status}</Body><View style={{ flexDirection:'row',gap:8,marginTop:10 }}><Button title="Accept" onPress={()=>r.updateReservationStatus(item.id,'confirmed')} style={{ minHeight:38 }}/><Button title="Decline" secondary onPress={()=>r.updateReservationStatus(item.id,'declined')} style={{ minHeight:38 }}/></View></Surface>):null}
 {tab==='Menu'?<><Surface><Title size={17}>Add menu item</Title><Field label="Dish name" value={name} onChangeText={setName}/><Field label="Price (Rs)" value={price} onChangeText={setPrice} keyboardType="number-pad"/><View style={{ flexDirection:'row',gap:8,marginBottom:12 }}>{['Starters','Mains','Desserts','Drinks'].map((x)=><Chip key={x} label={x} selected={category===x} onPress={()=>setCategory(x)}/>)}</View><Button title="Add item" onPress={()=>{if(!name.trim()||!Number(price)){Alert.alert('Missing details','Enter a dish name and valid price.');return;}addItem({name:name.trim(),description:'Added by restaurant manager.',price:Number(price),category});setName('');setPrice('');}}/></Surface>{items.map((item)=><Surface key={item.id} style={{ marginTop:9 }}><View style={{ flexDirection:'row',justifyContent:'space-between' }}><View style={{ flex:1 }}><Text style={{ color:colors.text,fontWeight:'800' }}>{item.name}</Text><Body>{item.category} · Rs {item.price} · {item.isAvailable?'Available':'Unavailable'}</Body></View><Button title={item.isAvailable?'86 item':'Restore'} secondary onPress={()=>updateItem(item.id,{isAvailable:!item.isAvailable})} style={{ minHeight:36 }}/></View><View style={{ flexDirection:'row',gap:7,marginTop:9 }}>{[item.price-50,item.price+50].filter((p)=>p>0).map((p)=><Button key={p} title={`Rs ${p}`} secondary onPress={()=>updateItem(item.id,{price:p})} style={{ minHeight:34 }}/>)}</View></Surface>)}</>:null}
 </Screen>;
}
