import React, { useState } from 'react';
import { Alert, Modal, Pressable, Text, View } from 'react-native';
import { Screen, Title, Body, Field, Button, Chip, Surface } from '../components/ui';
import useReservation from '../hooks/useReservation';
import { useTheme } from '../context/ThemeContext';
export default function ReservationScreen() {
 const r=useReservation(),{colors}=useTheme();const [showConfirm,setShowConfirm]=useState(false);
 const proceed=()=>{const error=r.validate();r.setError(error);if(error)return;setShowConfirm(true);};
 const save=()=>{const result=r.createReservation();if(result){setShowConfirm(false);Alert.alert('Reservation requested',`Table ${result.tableId} for ${result.partySize} at ${result.time}.`);}};
 return <Screen scroll><Title>Book a table</Title><Body style={{ marginTop:5,marginBottom:18 }}>Pick a time; unavailable slots are disabled for your party size.</Body><Surface><Field label="Date (YYYY-MM-DD)" value={r.date} onChangeText={r.setDate} placeholder="2026-10-01"/><Field label="Party size (1–12)" value={r.partySize} onChangeText={r.setPartySize} keyboardType="number-pad"/><Text style={{ color:colors.text,fontWeight:'800',marginBottom:10 }}>Available hourly slots</Text><View style={{ flexDirection:'row',flexWrap:'wrap',gap:8 }}>{r.availableSlots.map(({slot,available})=><Chip key={slot} label={slot} selected={r.time===slot} disabled={!available} onPress={()=>r.setTime(slot)}/>)}</View><Field label="Contact name" value={r.contactName} onChangeText={r.setContactName}/><Field label="Phone (03XX-XXXXXXX)" value={r.phone} onChangeText={r.setPhone} keyboardType="phone-pad" placeholder="0300-1234567"/>{r.error?<Text style={{ color:colors.danger,marginBottom:10,fontSize:12 }}>{r.error}</Text>:null}<Button title="Review reservation" onPress={proceed}/></Surface>
 <Title size={19} style={{ marginTop:24 }}>My reservations</Title>{r.myReservations.filter((x)=>x.status!=='cancelled').length===0?<Body style={{ marginTop:8 }}>No active reservations yet.</Body>:r.myReservations.filter((x)=>x.status!=='cancelled').map((item)=><Surface key={item.id} style={{ marginTop:10 }}><View style={{ flexDirection:'row',justifyContent:'space-between',gap:10 }}><View style={{ flex:1 }}><Text style={{ color:colors.text,fontWeight:'800' }}>{item.date} · {item.time}</Text><Body>{item.partySize} guests · {item.tableId} · {item.status}</Body></View><Pressable onPress={()=>Alert.alert('Cancel reservation?','This booking will be marked as cancelled.',[{text:'Keep booking',style:'cancel'},{text:'Cancel booking',style:'destructive',onPress:()=>r.cancelReservation(item.id)}])}><Text style={{ color:colors.danger,fontWeight:'800' }}>Cancel</Text></Pressable></View></Surface>)}
 <Modal visible={showConfirm} transparent animationType="fade" onRequestClose={()=>setShowConfirm(false)}><View style={{ flex:1,backgroundColor:'#0008',justifyContent:'center',padding:24 }}><Surface style={{ padding:20 }}><Title size={20}>Confirm booking</Title><Body style={{ marginTop:9 }}>Date {r.date} · {r.time}{'\n'}Party of {r.partySize} · {r.contactName}{'\n'}Phone {r.phone}</Body><View style={{ flexDirection:'row',gap:9,marginTop:18 }}><Button title="Go back" secondary onPress={()=>setShowConfirm(false)} style={{ flex:1 }}/><Button title="Confirm" onPress={save} style={{ flex:1 }}/></View></Surface></View></Modal>
 </Screen>;
}
